### ISSUE TITLE
Save changes button triggers Leave site? dialog in Chrome 72.0.3626.119

### ISSUE THREAD

**Issue by jsoref** [operasoftware/dns-ui#127]
1. visit `/dnsui/zones/example.com`
1. click the blank row
1. *name*: `a`
1. *type*: `a`
1. *content*: `127.0.0.1`
1. click `+ Add`
1. click `Save changes`

Actual results:
![image](https://user-images.githubusercontent.com/2119212/53902050-5453ab00-400e-11e9-80fb-89f3510613a2.png)

Clicking the `Leave` button results in the changes being saved. But this workflow is suboptimal.

Note:
Closing the tab (e.g. w/ cmd-w) results in the same dialog, which means that one can't tell when the dialog is warning about actual dataloss or content submission.

**Comment by thomas-pike** [comment]
I cannot reproduce the problem here. It is certainly supposed to appear (by design) when closing the tab, but the [javascript code](https://github.com/operasoftware/dns-ui/blob/master/public_html/extra.js#L610) is supposed to prevent it from displaying when actually saving changes.

**Comment by jsoref** [comment]
I'm hitting an exception here:
https://github.com/operasoftware/dns-ui/blob/000e9f3aca0f370c3d84f763b5dfab3a295d4bb3/public_html/extra.js#L604
`form.data is not a function`.

We're running https://github.com/operasoftware/dns-ui/commit/678206a33849ca9783d90419aba2b99b2447751f

**Comment by thomas-pike** [comment]
Interesting. Very interesting.

Looks like the bug was introduced in fc410df (specifically [this line](https://github.com/operasoftware/dns-ui/commit/fc410dfe1a0fc3ebe1dc015161205ae25501448a#diff-6caebd6ad61ef4475f45db4c961b4595R586)) but I'm not sure why I'm not seeing the effects of this bug.

**Comment by thomas-pike** [comment]
Regardless of me not being able to reproduce the error, the code is clearly broken. Please try #128 and see if that resolves it for you.
